site_name: Pipeline de Dados - Arquitetura Medalhão
theme:
  name: material
nav:
  - Início: index.md
  - Arquitetura: arquitetura.md
  - Pipeline: pipeline.md
  - Fluxo de Camadas: fluxo.md
  - Camadas:
      - Bronze: bronze.md
      - Silver: silver.md
      - Gold: gold.md
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
