[project]
name = "pipeline-dados-databricks"
version = "0.1.0"
description = "Documentação do pipeline Databricks seguindo arquitetura medalhão"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "material>=0.1",
    "mkdocs-material>=9.6.22",
    "pymdown-extensions>=10.16.1",
]
